### ISSUE TITLE
Cannot launch GUI apps after using duppy

### ISSUE THREAD

**Issue by t3st3d** [g0rbe/duppy#1]
Hi, great script, however after using it, it change the hostname making launching a graphical applications (wireshark,ZAP...) not possible because the user is seen as a remote host.

I'm also using Parrot, and since you tested it on it, how did you find a way around that problem ?
Also sometimes after using duppy, i cannot connect anymore to an access point and have to reboot the system, restarting the service does not work.

You might want to use "hostnamectl" instead of "hostname".

**Comment by t3st3d** [comment]
Thanks, i have to correct something though. Most applications that are graphical work with duppy activated, it's only when ran with root privilege that it fails.

**Comment by g0rbe** [comment]
Should work now. Missed the X authority file.
Thanks for reporting it!

**Comment by t3st3d** [comment]
It's working great, graphical applications run as root without issues, but i noticed after a reboot that it is not possible to connect anymore to a session with lightdm. The issue probably come from X authority (before rebooting i did `duppy stop`). Doing ALT+F1 to go in tty and typing `startx`will just hang, but if you use CTRL+C multiple times it will start X session, but it has to be done at each boot, lightdm won't work.

Can you confirm you have the same problem ?

**Comment by g0rbe** [comment]
Yeah, the only solution at now is delete the .Xauthority at shutdown or in tty.

**Comment by g0rbe** [comment]
It works now, please test it and if its work for you , please close the issue

**Comment by t3st3d** [comment]
I rebooted twice on a new VM to be sure and it's working without any problems, thanks. Even the error message about "resolve hostname" won't show up anymore so you might want to remove the notification about it.
